[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llm-sdk",
    "moulinette",
    "numpy>=2.5.2",
    "pydantic>=2.13.4",
]

[tool.uv.workspace]
members = [
    "llm_sdk",
    "moulinette",
]

[tool.uv.sources]
llm-sdk = { workspace = true }
moulinette = { workspace = true }
